
  // This file is auto-generated by .github/get_stats.py (do not edit locally)

  export const InvenTreeStats : any = {
    docker_pulls: 2409084,
    github_stars: 3211,
    github_forks: 561,
    github_contributors: 74,
    crowdin_languages: 30
  };

  