
title: InvenTree
tagline: Intuitive Inventory Management
demo-link: https://demo.inventreedb.com/
doc-link: https://inventree.readthedocs.io/en/latest/
plugin-link: https://repo.invenhost.com/

description: >-
  InvenTree is an open-source inventory management system which provides intuitive parts management and stock control.
  It is at the center of an ecosystem of addins for EDA and CAD tools, API wrapper, deeply integrated plugins and 3rd party tools.

baseurl: "/home.invenhost.com"
url: ""


plugins:
  - jekyll-seo-tag
  - jekyll-postcss-v2

exclude: [
  styles/index.css,
  styles/syntax.css,
  package.json,
  package-lock.json,
  postcss.config.js,
]
